#pragma once

#include "expressions/access.h"
#include "expressions/binary.h"
#include "expressions/get_value.h"
#include "expressions/length.h"
#include "expressions/literal.h"
#include "expressions/new.h"
#include "expressions/new_array.h"
#include "expressions/not.h"
#include "expressions/this.h"
#include "expressions/invocation.h"
#include "expressions/lvalue.h"

#include "statements/assert.h"
#include "statements/assign.h"
#include "statements/if_then.h"
#include "statements/if_then_else.h"
#include "statements/invocation.h"
#include "statements/return.h"
#include "statements/scope.h"
#include "statements/statement_list.h"
#include "statements/while.h"
#include "statements/declaration.h"
#include "statements/println.h"

#include "operators/dampersand.h"
#include "operators/dassign.h"
#include "operators/dpipe.h"
#include "operators/lts.h"
#include "operators/rts.h"
#include "operators/minus.h"
#include "operators/percent.h"
#include "operators/plus.h"
#include "operators/slash.h"
#include "operators/star.h"

#include "declarations.h"
#include "program.h"